# This uses a reusable workflow
name: Set due date to closed issue

on:
  issues:
    types: [closed]

jobs:
  set_due_date_to_closed_issue:
    uses: o-futuro-ja-comecou/github-actions-reutilizaveis/.github/workflows/set_due_date_to_closed_issue_reusable.yml@RELEASE_VERSION
    secrets:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        PROJECT_NUMBER: ${{ secrets.PROJECT_NUMBER }}
